# Generated by Django 5.0.3 on 2024-04-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_producto_cantidad_alter_producto_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default='Alimento', max_length=100),
        ),
    ]
