# Generated by Django 5.0.3 on 2024-04-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_jornadaayuda_dinero_dinerojornada_productojornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaayuda',
            name='es_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jornadaayuda',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
    ]
