# Generated by Django 5.0.3 on 2024-04-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_jornadaayuda_es_finalizado_jornadaayuda_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadaayuda',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
