# Generated by Django 5.0.3 on 2024-04-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_remove_jornadaayuda_fecha'),
        ('Personas', '0005_alter_patrocinador_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsablesJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='admin', max_length=100)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.jornadaayuda')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personas.patrocinador')),
            ],
        ),
    ]
