# Generated by Django 5.0.3 on 2024-04-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_responsablesjornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornadaayuda',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
