# Generated by Django 5.0.3 on 2024-04-21 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_jornadaayuda_fecha_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productojornada',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='productojornada',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='responsablesjornada',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='responsablesjornada',
            name='responsable',
        ),
        migrations.AddField(
            model_name='jornadaayuda',
            name='cantidad_fondos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='jornadaayuda',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jornadaayuda',
            name='fondos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.dinero'),
        ),
        migrations.AddField(
            model_name='jornadaayuda',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.producto'),
        ),
        migrations.DeleteModel(
            name='DineroJornada',
        ),
        migrations.DeleteModel(
            name='ProductoJornada',
        ),
        migrations.DeleteModel(
            name='ResponsablesJornada',
        ),
    ]
