# Generated by Django 5.1.3 on 2024-11-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('tipo_id', models.CharField(default='CC', max_length=20)),
                ('identificacion', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(default='Soltero(a)', max_length=20)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=20)),
                ('telefono', models.CharField(default='0', max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('es_discapacitado', models.BooleanField(default=False)),
                ('es_victima', models.BooleanField(default=False)),
                ('es_desplazado', models.BooleanField(default=False)),
                ('es_censado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(default='0', max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
