# Generated by Django 5.0.3 on 2024-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='estado_civil',
            field=models.CharField(default='Soltero(a)', max_length=20),
        ),
    ]
