# Generated by Django 5.0.3 on 2024-04-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_beneficiario_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='identificacion',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
