# Generated by Django 5.0.3 on 2024-04-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_beneficiario_created_at_beneficiario_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('NIT', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(default='0', max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
